### ISSUE TITLE
Consent based Usage Data Collection

### ISSUE THREAD

**Issue by flectrahqadmin** [flectrahq/discussion#28]
Currently Odoo collects user data using a cron job "Update Notification" and collects following data 

> {'web_base_url': u'http://localhost:8069', 'nbr_active_users': 1L, 'nbr_active_share_users': 0L, 'nbr_share_users': 1L, 'dbuuid': u'c5809a34-33d3-11e7-b849-000c2990739a', 'db_create_date': u'2017-05-08 09:50:30', 'dbname': 'test_odoo', 'name': u'YourCompany', 'language': u'en_US', 'phone': u'+1 555 123 8069', 'nbr_users': 3L, 'apps': [u'mail', u'account'], 'id': 1, 'enterprise_code': False, 'version': '10.0', 'email': u'info@yourcompany.example.com'}

This kind of data collection MUST be based on consent of user only, so there has to be a way to "Ask User" for it and way to "turn it off" as well.

**Comment by lisandi** [comment]
This is very important as otherwise clients could get in real trouble with the lawinforcement i.e. in Germany and the EU
