### ISSUE TITLE
Replace the JS framework with a best one line Angular2, React etc.

### ISSUE THREAD

**Issue by slimit** [flectrahq/discussion#30]
As I know Odoo is already working on a new JS framework which is a must have improvement since the actual one is very limited and make the new modules UI very limited.

In a quick comparison the new Angular version seems to be very promising.

More infos @ https://github.com/OCA/web/issues/562

**Comment by flectrahqadmin** [comment]
it is good idea but requires lot of re-write from scratch including XML views and re-implementation of lot many other JS related developments. May be we can consider this in our future road map.
