### ISSUE TITLE
Python 3.5

### ISSUE THREAD

**Issue by lisandi** [flectrahq/discussion#33]
It would be good to have FlectraHQ like Odoo11 available as a Python 3.5 **only** version. #1 and a way - tutorial - on how to move existing ODOO Modules 7,8,9,10,11 to FlectraHQ in Python 3.5.

**Comment by flectrahqadmin** [comment]
#1 is already being done by Odoo, so we stopped efforts from our side the moment we decided to fork v11 and found out that Odoo is doing them self. 

For moving modules to existing Odoo version, I doubt any single script will be useful as they'll also need to change code as per new version's structure. 

The best we can do is give a "Cheat Sheet" for moving existing Python v2.x series code to Python 3.5 and way to check if it's compatible or not.
