### ISSUE TITLE
ORM mapper to connect to multiple databases (MySQL, Oracle, ?SQL-Server?, PostgreSQL, SQLite (quick test, odoo-pocket), ...)

### ISSUE THREAD

**Issue by mwellnitz** [flectrahq/discussion#43]
It would be a great feature to use already installed professional databases in companies.
The most important will be MySQL/MariaDB but Oracle or even SQLite should be possible.
odoo already has an orm-abstraction layer. Professionals tend to use more professional databases than PostgreSQL. It would be a big PLUS for FlectraHQ to run on top of MySQL, SQL-Server or Oracle.

**Comment by Yakulu** [comment]
I disagree : PostgreSQL is a fantastic open source database. I think usage of advanced PotsgreSQL features would be a plus for Flectra (like hstore, JSONB, replication etc). The more you abstract, the more you need to support multiple databases, the less denominator you suffer from.

**Comment by mwellnitz** [comment]
I got your point and agree with you: PostgreSQL is a fantastic open source database. But did you got my point?

**Comment by Yakulu** [comment]
Yes but what is really the need ?

As Flectra is an ERP that obviously require dedicated or virtual server. You have to install the database by yourself, as Odoo itself (PostgreSQL runs well everywhere, can be installed without charge). What can bring , technical or functional advantages the support for SQL Server or Oracle ?

My point is when you decide to support multiple databases, you reduce your software capacities or you increase complexities and so the maintenance burden.

**Comment by flectrahqadmin** [comment]
@Yakulu Agree with his points, Adding support for multiple database actually degrades lots of things and have more-adverse effects, using a single database system makes thing more reliable and constant.

**Comment by mwellnitz** [comment]
If you have an already running database you also have an already running backup concept (in professional manner). Also your database machine(s) are deeply __hidden__ and much more safe then an application server. 
In this scenario the odoo instance can be a stupid VM build up with orchestration tools like ansible and there is no need to backup anything except the database (am i right?). In an enterprise setup it would be an advantage (big big big PLUS) not to depend on a specific database enginge.
Different engines have their own advantages and disadvantages and if you have the choice you will have a choice ;-) .
