### ISSUE TITLE
Let FlectraHQ support Galera Cluster

### ISSUE THREAD

**Issue by mwellnitz** [flectrahq/discussion#44]
# Why is Galera neccessary?
In high workload sites each second of downtime will lead to a **loss of revenue**. 
In case of a webshop it can lead to a **loss of customers**.
The **architecture of odoo** is devided into 3 tires:
1. web tier (nginx, apache, iis, lighttpd, etc.)
2. application tier (the odoo instance)
3. database tier (currently only postgres)
At time of writing there is no master-master setup possible in postgres: https://www.postgresql.org/docs/9.6/static/high-availability.html
From the **administrators point of view** nearly no other solution is as smart as Galera when it comes to upgrade/reboot cycles. You will have **no downtime** even if you have to remoot machines in case of kernel or security upgrades.
From the **salesman point of view** Galera-MySQL/MariaDB are well known as **rock solid** solutions in todays business. That could be a strong argument for selling an ERP system.

**Comment by flectrahqadmin** [comment]
As mentioned in #44 No other database support is planned as of now.

**Comment by mwellnitz** [comment]
soviel zu:
> Ja, wir würden gerne erfahren, was in FlectraHQ sein sollte und wie wir es erweitern können.

aus: https://flectrahq.com/de_CH/page/about_us

Keine 30 Minuten bis zum Abschuss des Vorschlags.
### Respekt

**Comment by thomich** [comment]
Hallo @mwellnitz 

Vielen Dank für Deine Input.
Wie bereits erwähnt im Moment ist kein anderer Support für Datenbank Systeme geplant.

Leider ist es nie möglich, alle Community Wünsche auf ein geplantes Feature Datum zu integrieren. Wir müssen auch Prioritäten setzen und sind offen für Vorschläge.

Unsere Liste von Verbesserungen, Inputs und Features steigt von Tag zu Tag...

Danke für Dein Verständnis.
