### ISSUE TITLE
Integration with Seafile

### ISSUE THREAD

**Issue by isos** [flectrahq/discussion#50]
It will be good to integrate with Seafile because is the most secure private cloud and is Open Source too.

**Comment by flectrahqadmin** [comment]
Instead of integrating with each of the cloud storage provider, we are thinking of using file system based approach where you can mount cloud storage as a "Directory" or "Drive" and then we can just put files / folder over there and rest is taken care automatically.

**Comment by isos** [comment]
yes, could be a good idea, thanks
