### ISSUE TITLE
App Builder - Resuing the Apps

### ISSUE THREAD

**Issue by nislinux** [flectrahq/discussion#57]
Hello Team,
App builder will be a game changer for sure,
An option to download the new app in .zip format will be another great thing, since the users can reuse the app which they built for one database in another. That is technically feasible right?

**Comment by rijulmanch** [comment]
Will make it easier to share apps with the community 👍

**Comment by nislinux** [comment]
True, it will serve as an option for non-technical users(who are sound in functional) make their ideas(requirements) into working modules.
But when it comes to sharing with the public - couple of other things also should be kept in mind:
1. The performance issue.
2. The optimum use of fileds and its behaviour in the view
3. During the version Upgradation of core - the behaviour of of modules created from app builder..etc
