### ISSUE TITLE
Ability to embed other webpages as a tab in Flectrahq

### ISSUE THREAD

**Issue by muguli22** [flectrahq/discussion#63]
It would be nice to have a way of embedding external web pages in to Flectrahq e.g from external BI tools websites

**Comment by flectrahqadmin** [comment]
@muguli22 you can always embed third party data / site snippets into web pages, it's just that site has to provide data in such a way, for example facebook, instagram, twitter, youtube all provides snippet to embed the data in other sites. no other coding required.

**Comment by muguli22** [comment]
thanks
