### ISSUE TITLE
Right to left culture

### ISSUE THREAD

**Issue by j209** [flectrahq/discussion#64]
Hi.
please implement rtl direction for cultures like arabic,hebr,persian... out of the box.

**Comment by thomich** [comment]
Hello @j209 

Thanks for input.
Translations are already there but we will make some changes after first release about right to left direction.

Regrds
thomi

**Comment by parthivgls** [comment]
@j209 it's in our roadmap, as RTL requires us to write some additional code on top of the current UI, we'll do it after our initial release.
