### ISSUE TITLE
Is Flectra real or is it a 1st april joke?

### ISSUE THREAD

**Issue by nafex** [flectrahq/discussion#8]
![image](https://cloud.githubusercontent.com/assets/4456069/24697326/0ced47d8-19ed-11e7-81ac-cc9537070669.png)

Flectra was announced on 1st april. Is it a joke or real?

Sorry for being skeptical :-)

**Comment by flectrahqadmin** [comment]
now it's 5. of april.. and we are still here.. so, is you question answered? ;)
